exports.tree = {
  value: [
    {
      teamTypeID: 1,
      teamTypeName: "Project Team",
      roleLevels: [
        {
          roleLevelId: 1,
          roleLevelNme: "Core",
          roles: [
            {
              roleId: 2,
              roleName: "Investment Officer - Portfolio",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 4,
              roleName: "Portfolio Assistant",
              primaryUsers: [
                {
                  id: 1,
                  upiNumber: 278622,
                  lastName: "Fadzai Kayinamura",
                  firstName: "Lillliossa",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "abc",
                  activeInd: "Y",
                  firstNameAndLastName: "Lillliossa Fadzai Kayinamura",
                },
              ],
              proxyUsers: [
                {
                  id: 2,
                  upiNumber: 278623,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "fdf",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
                {
                  upiNumber: 278624,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "abcdef",
                },
                {
                  upiNumber: 278625,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "123",
                },

                {
                  upiNumber: 278626,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
                {
                  upiNumber: 278627,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
                {
                  upiNumber: 278623,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
                {
                  upiNumber: 278624,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "abcdef",
                },
                {
                  upiNumber: 278625,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "123",
                },

                {
                  upiNumber: 278626,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
                {
                  upiNumber: 278627,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
              ],
            },
            {
              roleId: 5,
              roleName: "Credit Officer",
              primaryUsers: [],
              proxyUsers: [
                {
                  upiNumber: 278628,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
              ],
            },
            {
              roleId: 6,
              roleName: "Syndication Officer - Portfolio",
              primaryUsers: [],
              proxyUsers: [],
            },
          ],
        },
        {
          roleLevelId: 3,
          roleLevelNme: "Central",
          roles: [
            {
              roleId: 5,
              roleName: "Credit Officer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 15,
              roleName: "E&S Risk Officer",
              primaryUsers: [],
              proxyUsers: [],
            },
          ],
        },
        {
          roleLevelId: 2,
          roleLevelNme: "Other/Extended",
          roles: [
            {
              roleId: 45,
              roleName: "Budget Officer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 53,
              roleName: "LCM Approver",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 54,
              roleName: "LCM Reviewer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 57,
              roleName: "IC Reform Reviewers",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 68,
              roleName: "Project Reader (or) View Only List",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 69,
              roleName: "No Access List",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 71,
              roleName: "Strictly Confidential Access",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 73,
              roleName: "COI Office",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 74,
              roleName: "Mobilization Reviewer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 75,
              roleName: "Public Disclosure Reviewer",
              primaryUsers: [],
              proxyUsers: [],
            },
          ],
        },
      ],
    },
    {
      teamTypeID: 1,
      teamTypeName: "Ui Project Team",
      roleLevels: [
        {
          roleLevelId: 1,
          roleLevelNme: "Core",
          roles: [
            {
              roleId: 2,
              roleName: "Investment Officer - Portfolio",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 4,
              roleName: "Portfolio Assistant",
              primaryUsers: [
                {
                  id: 1,
                  upiNumber: 278622,
                  lastName: "Fadzai Kayinamura",
                  firstName: "Lillliossa",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "abc",
                  activeInd: "Y",
                  firstNameAndLastName: "Lillliossa Fadzai Kayinamura",
                },
              ],
              proxyUsers: [
                {
                  id: 2,
                  upiNumber: 278623,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "fdf",
                  activeInd: "Y",
                  firstNameAndLastName: "jk Brenda Kalenga",
                },
                {
                  upiNumber: 278624,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "jitendra kumar",
                },
                {
                  upiNumber: 278625,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "jayanth",
                },

                {
                  upiNumber: 278626,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "roy Kalenga",
                },
                {
                  upiNumber: 278627,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "joy Kalenga",
                },
                {
                  upiNumber: 278623,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "toy Kalenga",
                },
                {
                  upiNumber: 278624,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "raman",
                },
                {
                  upiNumber: 278625,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "syam",
                },

                {
                  upiNumber: 278626,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: " Kalenga",
                },
                {
                  upiNumber: 278627,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
              ],
            },
            {
              roleId: 5,
              roleName: "Credit Officer",
              primaryUsers: [],
              proxyUsers: [
                {
                  upiNumber: 278628,
                  lastName: "Kalenga",
                  firstName: "Brenda",
                  officePhoneNumber: "G-08",
                  phoneNumber: "731-3075",
                  email: "LKalenga@ifc.org",
                  titleName: "Portfolio Analyst",
                  activeInd: "Y",
                  firstNameAndLastName: "Brenda Kalenga",
                },
              ],
            },
            {
              roleId: 6,
              roleName: "Syndication Officer - Portfolio",
              primaryUsers: [],
              proxyUsers: [],
            },
          ],
        },
        {
          roleLevelId: 3,
          roleLevelNme: "Central",
          roles: [
            {
              roleId: 5,
              roleName: "Credit Officer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 15,
              roleName: "E&S Risk Officer",
              primaryUsers: [],
              proxyUsers: [],
            },
          ],
        },
        {
          roleLevelId: 2,
          roleLevelNme: "Other/Extended",
          roles: [
            {
              roleId: 45,
              roleName: "Budget Officer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 53,
              roleName: "LCM Approver",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 54,
              roleName: "LCM Reviewer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 57,
              roleName: "IC Reform Reviewers",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 68,
              roleName: "Project Reader (or) View Only List",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 69,
              roleName: "No Access List",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 71,
              roleName: "Strictly Confidential Access",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 73,
              roleName: "COI Office",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 74,
              roleName: "Mobilization Reviewer",
              primaryUsers: [],
              proxyUsers: [],
            },
            {
              roleId: 75,
              roleName: "Public Disclosure Reviewer",
              primaryUsers: [],
              proxyUsers: [],
            },
          ],
        },
      ],
    },
  ],

  isSuccess: true,
  isFailure: false,
  error: {
    code: "",
    message: "",
  },
};
